//CALORIES CONSTANTS

export const CALORIES_LIST_REQUEST = "CALORIES_LIST_REQUEST";
export const CALORIES_LIST_SUCCESS = "CALORIES_LIST_SUCCESS";
export const CALORIES_LIST_FAILURE = "CALORIES_LIST_FAILURE";

//CALORIES AVERAGE CONSTANTS

export const CALORIES_LIST_AVG_REQUEST = "CALORIES_LIST_AVG_REQUEST";
export const CALORIES_LIST_AVG_SUCCESS = "CALORIES_LIST_AVG_SUCCESS";
export const CALORIES_LIST_AVG_FAILURE = "CALORIES_LIST_AVG_FAILURE";

//TOTAL ENTRIES

export const TOTAL_ENTRIES_REQUEST = "TOTAL_ENTRIES_REQUEST";
export const TOTAL_ENTRIES_SUCCESS = "TOTAL_ENTRIES_SUCCESS";
export const TOTAL_ENTRIES_FAILURE = "TOTAL_ENTRIES_FAILURE";
