//User Constants

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAILURE = "LIST_USER_FAILURE";

// ADD USER CONSTANTS

export const ADD_LIST_USER_REQUEST = "ADD_LIST_USER_REQUEST";
export const ADD_LIST_USER_SUCCESS = "ADD_LIST_USER_SUCCESS";
export const ADD_LIST_USER_FAILURE = "ADD_LIST_USER_FAILURE";

//User TOTAL CALORIES Constants

export const LIST_USER_CALORIES_REQUEST = "LIST_USER_CALORIES_REQUEST";
export const LIST_USER_CALORIES_SUCCESS = "LIST_USER_CALORIES_SUCCESS";
export const LIST_USER_CALORIES_FAILURE = "LIST_USER_CALORIES_FAILURE";
