//ADMIN Constants

export const ADMIN_LIST_REQUEST = "ADMIN_LIST_REQUEST";
export const ADMIN_LIST_SUCCESS = "ADMIN_LIST_SUCCESS";
export const ADMIN_LIST_FAILURE = "ADMIN_LIST_FAILURE";

// ADD ADMIN CONSTANTS

export const ADD_LIST_ADMIN_REQUEST = "ADD_LIST_ADMIN_REQUEST";
export const ADD_LIST_ADMIN_SUCCESS = "ADD_LIST_ADMIN_SUCCESS";
export const ADD_LIST_ADMIN_FAILURE = "ADD_LIST_ADMIN_FAILURE";

// EDIT ADMIN CONSTANTS

export const EDIT_ADMIN_LIST_REQUEST = "EDIT_ADMIN_LIST_REQUEST";
export const EDIT_ADMIN_LIST_SUCCESS = "EDIT_ADMIN_LIST_SUCCESS";
export const EDIT_ADMIN_LIST_FAILURE = "EDIT_ADMIN_LIST_FAILURE";

// UPDATE ADMIN CONSTANTS

export const UPDATE_ADMIN_LIST_REQUEST = "UPDATE_ADMIN_LIST_REQUEST";
export const UPDATE_ADMIN_LIST_SUCCESS = "UPDATE_ADMIN_LIST_SUCCESS";
export const UPDATE_ADMIN_LIST_FAILURE = "UPDATE_ADMIN_LIST_FAILURE";
export const UPDATE_ADMIN_LIST_RESET = "UPDATE_ADMIN_LIST_RESET";

// DELETE ADMIN CONSTANTS

export const DELETE_ADMIN_LIST_REQUEST = "DELETE_ADMIN_LIST_REQUEST";
export const DELETE_ADMIN_LIST_SUCCESS = "DELETE_ADMIN_LIST_SUCCESS";
export const DELETE_ADMIN_LIST_FAILURE = "DELETE_ADMIN_LIST_FAILURE";

//ADMIN USER DROPDOWN Constants

export const ADMIN_USER__DROPDOWN_REQUEST = "ADMIN_USER__DROPDOWN_REQUEST";
export const ADMIN_USER__DROPDOWN_SUCCESS = "ADMIN_USER__DROPDOWN_SUCCESS";
export const ADMIN_USER__DROPDOWN_FAILURE = "ADMIN_USER__DROPDOWN_FAILURE";
