# Generated by Django 4.1.1 on 2022-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories_threshold',
            field=models.FloatField(default=2100),
        ),
    ]
